<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from com.skvare.fileanalyzer/xml/schema/CRM/Fileanalyzer/FileanalyzerDeleted.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:444ad4266891666b2dacbb9140df8118)
 */
use CRM_Fileanalyzer_ExtensionUtil as E;

/**
 * Database access object for the FileanalyzerDeleted entity.
 */
class CRM_Fileanalyzer_DAO_FileanalyzerDeleted extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_file_analyzer_deleted';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique FileanalyzerDeleted ID
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $id;

  /**
   * Original file analyzer record ID
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $file_analyzer_id;

  /**
   * Name of deleted file
   *
   * @var string
   *   (SQL type: varchar(255))
   *   Note that values will be retrieved from the database as a string.
   */
  public $filename;

  /**
   * Original file path
   *
   * @var string
   *   (SQL type: varchar(500))
   *   Note that values will be retrieved from the database as a string.
   */
  public $file_path;

  /**
   * Directory type
   *
   * @var string
   *   (SQL type: varchar(20))
   *   Note that values will be retrieved from the database as a string.
   */
  public $directory_type;

  /**
   * File size in bytes
   *
   * @var string
   *   (SQL type: bigint unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $file_size;

  /**
   * File extension
   *
   * @var string|null
   *   (SQL type: varchar(10))
   *   Note that values will be retrieved from the database as a string.
   */
  public $file_extension;

  /**
   * Path to backup copy if exists
   *
   * @var string|null
   *   (SQL type: varchar(500))
   *   Note that values will be retrieved from the database as a string.
   */
  public $backup_path;

  /**
   * Contact ID who deleted the file
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $deleted_by;

  /**
   * When file was deleted
   *
   * @var string
   *   (SQL type: datetime)
   *   Note that values will be retrieved from the database as a string.
   */
  public $deleted_date;

  /**
   * Method: manual, auto, bulk
   *
   * @var string|null
   *   (SQL type: varchar(50))
   *   Note that values will be retrieved from the database as a string.
   */
  public $deletion_method;

  /**
   * Whether file was abandoned at deletion
   *
   * @var bool|string
   *   (SQL type: tinyint)
   *   Note that values will be retrieved from the database as a string.
   */
  public $was_abandoned;

  /**
   * Reason or notes for deletion
   *
   * @var string|null
   *   (SQL type: text)
   *   Note that values will be retrieved from the database as a string.
   */
  public $deletion_reason;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_file_analyzer_deleted';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Fileanalyzer Deleteds') : E::ts('Fileanalyzer Deleted');
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('ID'),
          'description' => E::ts('Unique FileanalyzerDeleted ID'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_file_analyzer_deleted.id',
          'table_name' => 'civicrm_file_analyzer_deleted',
          'entity' => 'FileanalyzerDeleted',
          'bao' => 'CRM_Fileanalyzer_DAO_FileanalyzerDeleted',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'file_analyzer_id' => [
          'name' => 'file_analyzer_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('File Analyzer ID'),
          'description' => E::ts('Original file analyzer record ID'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_file_analyzer_deleted.file_analyzer_id',
          'table_name' => 'civicrm_file_analyzer_deleted',
          'entity' => 'FileanalyzerDeleted',
          'bao' => 'CRM_Fileanalyzer_DAO_FileanalyzerDeleted',
          'localizable' => 0,
          'FKClassName' => 'CRM_Fileanalyzer_DAO_Fileanalyzer',
          'html' => [
            'type' => 'EntityRef',
            'label' => E::ts("File Analyzer"),
          ],
          'add' => NULL,
        ],
        'filename' => [
          'name' => 'filename',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Filename'),
          'description' => E::ts('Name of deleted file'),
          'required' => TRUE,
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_file_analyzer_deleted.filename',
          'table_name' => 'civicrm_file_analyzer_deleted',
          'entity' => 'FileanalyzerDeleted',
          'bao' => 'CRM_Fileanalyzer_DAO_FileanalyzerDeleted',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
            'label' => E::ts("Filename"),
          ],
          'add' => NULL,
        ],
        'file_path' => [
          'name' => 'file_path',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('File Path'),
          'description' => E::ts('Original file path'),
          'required' => TRUE,
          'maxlength' => 500,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_file_analyzer_deleted.file_path',
          'table_name' => 'civicrm_file_analyzer_deleted',
          'entity' => 'FileanalyzerDeleted',
          'bao' => 'CRM_Fileanalyzer_DAO_FileanalyzerDeleted',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
            'label' => E::ts("File Path"),
          ],
          'add' => NULL,
        ],
        'directory_type' => [
          'name' => 'directory_type',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Directory Type'),
          'description' => E::ts('Directory type'),
          'required' => TRUE,
          'maxlength' => 20,
          'size' => CRM_Utils_Type::MEDIUM,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_file_analyzer_deleted.directory_type',
          'table_name' => 'civicrm_file_analyzer_deleted',
          'entity' => 'FileanalyzerDeleted',
          'bao' => 'CRM_Fileanalyzer_DAO_FileanalyzerDeleted',
          'localizable' => 0,
          'html' => [
            'type' => 'Select',
            'label' => E::ts("Directory Type"),
          ],
          'pseudoconstant' => [
            'callback' => 'CRM_Fileanalyzer_BAO_FileAnalyzerDeleted::getDirectoryTypes',
          ],
          'add' => NULL,
        ],
        'file_size' => [
          'name' => 'file_size',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('File Size'),
          'description' => E::ts('File size in bytes'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_file_analyzer_deleted.file_size',
          'default' => '0',
          'table_name' => 'civicrm_file_analyzer_deleted',
          'entity' => 'FileanalyzerDeleted',
          'bao' => 'CRM_Fileanalyzer_DAO_FileanalyzerDeleted',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
            'label' => E::ts("File Size"),
          ],
          'add' => NULL,
        ],
        'file_extension' => [
          'name' => 'file_extension',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('File Extension'),
          'description' => E::ts('File extension'),
          'maxlength' => 10,
          'size' => CRM_Utils_Type::TWELVE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_file_analyzer_deleted.file_extension',
          'table_name' => 'civicrm_file_analyzer_deleted',
          'entity' => 'FileanalyzerDeleted',
          'bao' => 'CRM_Fileanalyzer_DAO_FileanalyzerDeleted',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
            'label' => E::ts("File Extension"),
          ],
          'add' => NULL,
        ],
        'backup_path' => [
          'name' => 'backup_path',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Backup Path'),
          'description' => E::ts('Path to backup copy if exists'),
          'maxlength' => 500,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_file_analyzer_deleted.backup_path',
          'table_name' => 'civicrm_file_analyzer_deleted',
          'entity' => 'FileanalyzerDeleted',
          'bao' => 'CRM_Fileanalyzer_DAO_FileanalyzerDeleted',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
            'label' => E::ts("Backup Path"),
          ],
          'add' => NULL,
        ],
        'deleted_by' => [
          'name' => 'deleted_by',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Deleted By'),
          'description' => E::ts('Contact ID who deleted the file'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_file_analyzer_deleted.deleted_by',
          'table_name' => 'civicrm_file_analyzer_deleted',
          'entity' => 'FileanalyzerDeleted',
          'bao' => 'CRM_Fileanalyzer_DAO_FileanalyzerDeleted',
          'localizable' => 0,
          'FKClassName' => 'CRM_Contact_DAO_Contact',
          'html' => [
            'type' => 'EntityRef',
            'label' => E::ts("Deleted By"),
          ],
          'add' => NULL,
        ],
        'deleted_date' => [
          'name' => 'deleted_date',
          'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
          'title' => E::ts('Deleted Date'),
          'description' => E::ts('When file was deleted'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_file_analyzer_deleted.deleted_date',
          'table_name' => 'civicrm_file_analyzer_deleted',
          'entity' => 'FileanalyzerDeleted',
          'bao' => 'CRM_Fileanalyzer_DAO_FileanalyzerDeleted',
          'localizable' => 0,
          'html' => [
            'type' => 'Select Date',
            'label' => E::ts("Deleted Date"),
          ],
          'add' => NULL,
        ],
        'deletion_method' => [
          'name' => 'deletion_method',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Deletion Method'),
          'description' => E::ts('Method: manual, auto, bulk'),
          'maxlength' => 50,
          'size' => CRM_Utils_Type::BIG,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_file_analyzer_deleted.deletion_method',
          'table_name' => 'civicrm_file_analyzer_deleted',
          'entity' => 'FileanalyzerDeleted',
          'bao' => 'CRM_Fileanalyzer_DAO_FileanalyzerDeleted',
          'localizable' => 0,
          'html' => [
            'type' => 'Select',
            'label' => E::ts("Deletion Method"),
          ],
          'pseudoconstant' => [
            'callback' => 'CRM_Fileanalyzer_BAO_FileAnalyzerDeleted::getDeletionMethods',
          ],
          'add' => NULL,
        ],
        'was_abandoned' => [
          'name' => 'was_abandoned',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'title' => E::ts('Was Abandoned'),
          'description' => E::ts('Whether file was abandoned at deletion'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_file_analyzer_deleted.was_abandoned',
          'default' => '0',
          'table_name' => 'civicrm_file_analyzer_deleted',
          'entity' => 'FileanalyzerDeleted',
          'bao' => 'CRM_Fileanalyzer_DAO_FileanalyzerDeleted',
          'localizable' => 0,
          'html' => [
            'type' => 'CheckBox',
            'label' => E::ts("Was Abandoned"),
          ],
          'add' => NULL,
        ],
        'deletion_reason' => [
          'name' => 'deletion_reason',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => E::ts('Deletion Reason'),
          'description' => E::ts('Reason or notes for deletion'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_file_analyzer_deleted.deletion_reason',
          'table_name' => 'civicrm_file_analyzer_deleted',
          'entity' => 'FileanalyzerDeleted',
          'bao' => 'CRM_Fileanalyzer_DAO_FileanalyzerDeleted',
          'localizable' => 0,
          'html' => [
            'type' => 'TextArea',
            'label' => E::ts("Deletion Reason"),
          ],
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'file_analyzer_deleted', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'file_analyzer_deleted', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [
      'index_directory_type' => [
        'name' => 'index_directory_type',
        'field' => [
          0 => 'directory_type',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_file_analyzer_deleted::0::directory_type',
      ],
      'index_deleted_date' => [
        'name' => 'index_deleted_date',
        'field' => [
          0 => 'deleted_date',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_file_analyzer_deleted::0::deleted_date',
      ],
      'index_deleted_by' => [
        'name' => 'index_deleted_by',
        'field' => [
          0 => 'deleted_by',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_file_analyzer_deleted::0::deleted_by',
      ],
    ];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
