-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables - this section generated from file:drop.tpl
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_file_analyzer_scan`;
DROP TABLE IF EXISTS `civicrm_file_analyzer_reference`;
DROP TABLE IF EXISTS `civicrm_file_analyzer_deleted`;
DROP TABLE IF EXISTS `civicrm_file_analyzer`;

SET FOREIGN_KEY_CHECKS=1;

-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_file_analyzer
-- *
-- * Tracks all files in CiviCRM directories with metadata and usage status
-- *
-- *******************************************************/
CREATE TABLE `civicrm_file_analyzer` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique Fileanalyzer ID',
  `file_id` int unsigned COMMENT 'Reference to civicrm_file.id if linked',
  `filename` varchar(255) NOT NULL COMMENT 'File name with extension',
  `file_path` varchar(500) NOT NULL COMMENT 'Full file path on server',
  `directory_type` varchar(20) NOT NULL COMMENT 'Directory type: custom, contribute',
  `file_size` bigint unsigned NOT NULL DEFAULT 0 COMMENT 'File size in bytes',
  `file_extension` varchar(10) COMMENT 'File extension (pdf, jpg, png, etc)',
  `mime_type` varchar(100) COMMENT 'MIME type of the file',
  `is_abandoned` tinyint NOT NULL DEFAULT 0 COMMENT 'Flag indicating if file is orphaned',
  `is_active` tinyint NOT NULL DEFAULT 1 COMMENT 'Flag indicating if file still exists on filesystem',
  `created_date` datetime COMMENT 'File creation date from filesystem',
  `modified_date` datetime COMMENT 'File last modification date',
  `last_scanned_date` datetime COMMENT 'Last time this file was scanned',
  `scan_status` varchar(20) DEFAULT "pending" COMMENT 'Status: pending, scanned, deleted, error',
  `is_contact_file` tinyint NOT NULL DEFAULT 1 COMMENT 'Flag indicating if file is belong contact image',
  `contact_id` int unsigned COMMENT 'FK to Contact',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_file_path_directory`(file_path, directory_type),
  INDEX `index_directory_type`(directory_type),
  INDEX `index_is_abandoned`(is_abandoned),
  INDEX `index_file_extension`(file_extension),
  INDEX `index_scan_status`(scan_status),
  INDEX `index_modified_date`(modified_date),
  CONSTRAINT FK_civicrm_file_analyzer_file_id FOREIGN KEY (`file_id`) REFERENCES `civicrm_file`(`id`) ON DELETE SET NULL,
  CONSTRAINT FK_civicrm_file_analyzer_contact_id FOREIGN KEY (`contact_id`) REFERENCES `civicrm_contact`(`id`) ON DELETE SET NULL)
ENGINE=InnoDB;

-- /*******************************************************
-- *
-- * civicrm_file_analyzer_deleted
-- *
-- * Audit trail of deleted files for compliance and recovery
-- *
-- *******************************************************/
CREATE TABLE `civicrm_file_analyzer_deleted` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique FileanalyzerDeleted ID',
  `file_analyzer_id` int unsigned COMMENT 'Original file analyzer record ID',
  `filename` varchar(255) NOT NULL COMMENT 'Name of deleted file',
  `file_path` varchar(500) NOT NULL COMMENT 'Original file path',
  `directory_type` varchar(20) NOT NULL COMMENT 'Directory type',
  `file_size` bigint unsigned NOT NULL DEFAULT 0 COMMENT 'File size in bytes',
  `file_extension` varchar(10) COMMENT 'File extension',
  `backup_path` varchar(500) COMMENT 'Path to backup copy if exists',
  `deleted_by` int unsigned COMMENT 'Contact ID who deleted the file',
  `deleted_date` datetime NOT NULL COMMENT 'When file was deleted',
  `deletion_method` varchar(50) COMMENT 'Method: manual, auto, bulk',
  `was_abandoned` tinyint NOT NULL DEFAULT 0 COMMENT 'Whether file was abandoned at deletion',
  `deletion_reason` text COMMENT 'Reason or notes for deletion',
  PRIMARY KEY (`id`),
  INDEX `index_directory_type`(directory_type),
  INDEX `index_deleted_date`(deleted_date),
  INDEX `index_deleted_by`(deleted_by),
  CONSTRAINT FK_civicrm_file_analyzer_deleted_file_analyzer_id FOREIGN KEY (`file_analyzer_id`) REFERENCES `civicrm_file_analyzer`(`id`) ON DELETE SET NULL,
  CONSTRAINT FK_civicrm_file_analyzer_deleted_deleted_by FOREIGN KEY (`deleted_by`) REFERENCES `civicrm_contact`(`id`) ON DELETE SET NULL)
ENGINE=InnoDB;

-- /*******************************************************
-- *
-- * civicrm_file_analyzer_reference
-- *
-- * Tracks where files are referenced/used in the system
-- *
-- *******************************************************/
CREATE TABLE `civicrm_file_analyzer_reference` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique FileanalyzerReference ID',
  `file_analyzer_id` int unsigned NOT NULL COMMENT 'Reference to civicrm_file_analyzer.id',
  `reference_type` varchar(50) NOT NULL COMMENT 'Type: file_record, contact_image, contribution_page, message_template, custom_field',
  `entity_table` varchar(64) COMMENT 'Related entity table name',
  `entity_id` int unsigned COMMENT 'Related entity ID',
  `field_name` varchar(100) COMMENT 'Field name where file is referenced',
  `reference_details` text COMMENT 'JSON with additional reference metadata',
  `created_date` datetime NOT NULL COMMENT 'When this reference was discovered',
  `last_verified_date` datetime COMMENT 'Last time reference was verified',
  `is_active` tinyint NOT NULL DEFAULT 1 COMMENT 'Whether reference is still valid',
  PRIMARY KEY (`id`),
  INDEX `index_reference_type`(reference_type),
  INDEX `index_entity`(entity_table, entity_id),
  CONSTRAINT FK_civicrm_file_analyzer_reference_file_analyzer_id FOREIGN KEY (`file_analyzer_id`) REFERENCES `civicrm_file_analyzer`(`id`) ON DELETE CASCADE)
ENGINE=InnoDB;

-- /*******************************************************
-- *
-- * civicrm_file_analyzer_scan
-- *
-- * Historical record of file analysis scans
-- *
-- *******************************************************/
CREATE TABLE `civicrm_file_analyzer_scan` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique FileanalyzerScan ID',
  `directory_type` varchar(20) NOT NULL COMMENT 'Directory type scanned',
  `scan_date` datetime NOT NULL COMMENT 'When scan was performed',
  `total_files_scanned` int unsigned NOT NULL DEFAULT 0 COMMENT 'Total files found',
  `active_files` int unsigned NOT NULL DEFAULT 0 COMMENT 'Files with references',
  `abandoned_files` int unsigned NOT NULL DEFAULT 0 COMMENT 'Files without references',
  `total_size` bigint unsigned NOT NULL DEFAULT 0 COMMENT 'Total size in bytes',
  `abandoned_size` bigint unsigned NOT NULL DEFAULT 0 COMMENT 'Abandoned files size in bytes',
  `scan_duration` int unsigned COMMENT 'Scan duration in seconds',
  `scan_status` varchar(20) DEFAULT "running" COMMENT 'Status: running, completed, failed',
  `error_message` text COMMENT 'Error details if scan failed',
  `statistics` text COMMENT 'JSON with detailed statistics',
  PRIMARY KEY (`id`),
  INDEX `index_directory_type`(directory_type),
  INDEX `index_scan_date`(scan_date),
  INDEX `index_scan_status`(scan_status))
ENGINE=InnoDB;
